---
title: "Beers Analysis Website"
author: "chloebarker19"
date: "2025-03-22"
output: html_document
runtime: shiny
---
### 1.	Let the user read in the data (the Beer Data.) 
### 2.	Let the user make a histogram of the IBU
### 3.	Let the user make a histogram of the ABV  (separate histogram)
### 4.	Low the user switch back and forth between histograms and boxplots to represent this information.  You could do this with a radio button that switches the plot from histogram to boxplot … the implementation however is up to you.  
### 5.	Allow the user to filter the histograms / boxplots above by state. 
### 6.	In addition to the histograms, add a scatter plot of IBU v. ABV
### 7.	Add the ability to add or take off the simple linear regression line. 
### 8.	Allow the user to filter the data on the scatter plot by state.
###9.	Add at least one additional plot from your analysis and make sure to clearly label and/or describe the information it is conveying.  
### 10.	Publish your app to ShinyApps.io

```{r}

library(dplyr)
library(readr)
library(tidyr)
library(ggthemes)
library(rsconnect)

rsconnect::setAccountInfo(name='chloebarker19',
                          token='7DA93DA65AB801B3AA100F78F49F9540',
                          secret='<SECRET>')
rsconnect::setAccountInfo(name='chloebarker19',token='7DA93DA65AB801B3AA100F78F49F9540',secret='<SECRET>')
rsconnect::deployApp('path/to/your/app')

# This is a Shiny web application. You can run the application by clicking
# the 'Run App' button above.
#
# Find out more about building applications with Shiny here:
#
#    http://shiny.rstudio.com/
#

beers = read.csv("Beers.csv", header = TRUE)
breweries = read.csv("Breweries.csv", header = TRUE)
beer_data = full_join(beers, breweries, by = "Brew_ID")
beer_data = rename(beer_data, Beer = Name.x, Brewery = Name.y)

sapply(beer_data, function(x) sum(is.na(x)))
# 62 Missing ABV and 1005 missing IBU 
beer_data = beer_data %>% select(Beer, IBU, ABV, State) %>% filter(!is.na(IBU)) 

```